"""PLCDataConfigテーブルを追加

Revision ID: 01004774a0ce
Revises: 3004db1eb255
Create Date: 2025-07-15 03:51:55.491899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01004774a0ce'
down_revision = '3004db1eb255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plc_data_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('scale_factor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'data_type', name='uq_equipment_data_type')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cycle_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('error_code')
        batch_op.drop_column('cycle_time')
        batch_op.drop_column('production_count')

    op.drop_table('plc_data_configs')
    # ### end Alembic commands ###
