"""ログテーブル最適化とインデックス追加

Revision ID: 193f267a3e72
Revises: 31ebb7e53291
Create Date: 2025-07-19 18:41:54.657219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193f267a3e72'
down_revision = '31ebb7e53291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_log_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('production_count_total', sa.Integer(), nullable=True),
    sa.Column('current_avg', sa.Float(), nullable=True),
    sa.Column('current_max', sa.Float(), nullable=True),
    sa.Column('current_min', sa.Float(), nullable=True),
    sa.Column('temperature_avg', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('pressure_avg', sa.Float(), nullable=True),
    sa.Column('pressure_max', sa.Float(), nullable=True),
    sa.Column('pressure_min', sa.Float(), nullable=True),
    sa.Column('cycle_time_avg', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('data_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'date', name='uq_equipment_date')
    )
    op.create_table('monthly_log_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('production_count_total', sa.Integer(), nullable=True),
    sa.Column('current_avg', sa.Float(), nullable=True),
    sa.Column('current_max', sa.Float(), nullable=True),
    sa.Column('current_min', sa.Float(), nullable=True),
    sa.Column('temperature_avg', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('pressure_avg', sa.Float(), nullable=True),
    sa.Column('cycle_time_avg', sa.Float(), nullable=True),
    sa.Column('error_count_total', sa.Integer(), nullable=True),
    sa.Column('operational_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'year', 'month', name='uq_equipment_year_month')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_log_summaries')
    op.drop_table('daily_log_summaries')
    # ### end Alembic commands ###
