"""Add JSON data columns for dynamic PLC fields

Revision ID: 27e1e8566303
Revises: 193f267a3e72
Create Date: 2025-10-16 16:19:07.189024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e1e8566303'
down_revision = '193f267a3e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_summary', sa.JSON(), nullable=True))

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    with op.batch_alter_table('monthly_log_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_summary', sa.JSON(), nullable=True))

    with op.batch_alter_table('plc_data_configs', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.drop_constraint(batch_op.f('uq_equipment_data_type'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plc_data_configs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_equipment_data_type'), ['equipment_id', 'data_type'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('monthly_log_summaries', schema=None) as batch_op:
        batch_op.drop_column('data_summary')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('daily_log_summaries', schema=None) as batch_op:
        batch_op.drop_column('data_summary')

    # ### end Alembic commands ###
