"""Add JSON data columns for dynamic PLC fields

Revision ID: 27e1e8566303
Revises: 193f267a3e72
Create Date: 2025-10-16 16:19:07.189024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e1e8566303'
down_revision = '193f267a3e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_summary', sa.JSON(), nullable=True))

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    with op.batch_alter_table('monthly_log_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_summary', sa.JSON(), nullable=True))

    # plc_data_configsテーブルに新しいカラムを追加
    with op.batch_alter_table('plc_data_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True, server_default=''))
        batch_op.add_column(sa.Column('icon', sa.String(length=10), nullable=True, server_default=''))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True, server_default=''))
        # plc_data_typeは既にb90e2093e414で追加されているため、ここでは追加しない

    # 既存のplc_data_typeカラムのNULL値をデフォルト値'word'で埋める
    op.execute("UPDATE plc_data_configs SET plc_data_type = 'word' WHERE plc_data_type IS NULL")

    # 既存データのnameをdata_typeで埋める
    op.execute("UPDATE plc_data_configs SET name = data_type WHERE name = '' OR name IS NULL")

    with op.batch_alter_table('plc_data_configs', schema=None) as batch_op:
        # nameをNOT NULLに変更
        batch_op.alter_column('name', nullable=False)
        # ユニーク制約を削除（動的項目対応のため）
        batch_op.drop_constraint('uq_equipment_data_type', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plc_data_configs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_equipment_data_type', ['equipment_id', 'data_type'])
        batch_op.alter_column('name', nullable=True)
        # plc_data_typeはb90e2093e414で追加されたため、ここでは削除しない（元の状態に戻すためNULLにする）
        batch_op.drop_column('unit')
        batch_op.drop_column('icon')
        batch_op.drop_column('name')

    with op.batch_alter_table('monthly_log_summaries', schema=None) as batch_op:
        batch_op.drop_column('data_summary')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('daily_log_summaries', schema=None) as batch_op:
        batch_op.drop_column('data_summary')

    # ### end Alembic commands ###
