"""cpuシリアル番号テーブル追加

Revision ID: 31ebb7e53291
Revises: de3007284f84
Create Date: 2025-07-19 02:35:29.714754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ebb7e53291'
down_revision = 'de3007284f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_serial_number', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['cpu_serial_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cpu_serial_number')

    # ### end Alembic commands ###
